language: ruby
rvm:
  - 2.3.0
#  - ruby-head
script: bundle exec jekyll build
after_success:
  - cat .travis/ssh-config >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_674d1c9f27ee_key -iv $encrypted_674d1c9f27ee_iv -in deploy.key.enc -out .travis/deploy.key -d
  - chmod 600 .travis/deploy.key
  - cp .travis/deploy.key ~/.ssh/
  - ls -alh --color ~/.ssh/
  - cat ~/.ssh/config
  - md5sum ~/.ssh/deploy.key
  - ssh ledyba@shell.osdn.jp id
  - rsync -rlOtv --delete --stats _site/ ledyba@shell.osdn.jp:/home/groups/s/sa/saccubus/htdocs
